# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-06-18 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_suppot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppot',
            new_name='Support',
        ),
    ]
