# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-06-18 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20160618_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_list', models.CharField(max_length=255)),
                ('unknown_list', models.CharField(max_length=255)),
                ('todo_list', models.CharField(max_length=255)),
                ('problem_statement', models.CharField(max_length=255)),
                ('conclusion', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
                ('teacher_point', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Problem')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
