# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-06-26 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_writeup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Writeup',
        ),
    ]
