# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-06-29 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20160626_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
