# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_problem_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='picture',
            new_name='picture_path',
        ),
        migrations.AddField(
            model_name='problem',
            name='picture_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
