# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20160708_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='picture_name',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
