# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20160708_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='picture_path',
            field=models.FileField(default='static/media/problem/default.jpg', upload_to='static/media/problem'),
        ),
    ]
