# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-08 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20160708_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='picture_path',
            new_name='picture',
        ),
    ]
