# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_remove_problem_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='picture',
            field=models.FileField(default='static/media/problem/picture/default.jpg', upload_to='static/media/problem/picture'),
        ),
    ]
