# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-10 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_problem_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='answer',
            new_name='correct',
        ),
    ]
