# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-10 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_auto_20160710_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='A',
            field=models.CharField(default='A', max_length=1024),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='B',
            field=models.CharField(default='B', max_length=1024),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='C',
            field=models.CharField(default='C', max_length=1024),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='D',
            field=models.CharField(default='D', max_length=1024),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='E',
            field=models.CharField(default='E', max_length=1024),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='correct',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='question',
            field=models.CharField(max_length=1024),
        ),
    ]
