# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_auto_20160710_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='difficult_level',
            field=models.CharField(max_length=2),
        ),
    ]
