# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-10 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_auto_20160710_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='answer',
            field=models.CharField(default='A', max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='difficult_level',
            field=models.CharField(max_length=255),
        ),
    ]
