# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_auto_20160710_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='A',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='B',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='C',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='D',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='E',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
