# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_auto_20160710_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='keyword',
            field=models.CharField(default='Fill your keyword here...', max_length=255),
        ),
    ]
