# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-23 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_problem_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
    ]
