from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse

urlpatterns = patterns('student.views',
	url(r'^$','index'),
	url(r'^about$','about'),
	url(r'^login$','login'),
	url(r'^login_error','login_error'),
	url(r'^logout$','logout'),
	url(r'^welcome$','welcome'),
	# url(r'^guide$','guide'),
	url(r'^problem/([\d]+)','problem'),
	url(r'^problem$','problem'),
	url(r'^problem/workspace/([\d]+)','workspace'),
	url(r'^problem/workspace/update/([\d]+)','workspace_update'),
	# url(r'^problem/workspace/update$','workspace_update'),
	url(r'^problem/workspace/check/answer$','check_answer'),
	url(r'^problem/workspace/evaluation/check/answer$','evaluation_check_answer'),
	url(r'^dashboard/([\d]+)','dashboard'),
	url(r'^dashboard$','dashboard'),
	url(r'^dashboard/update/([\d]+)','dashboard_update'),
	url(r'^team/([\d]+)','team'),
	url(r'^team$','team'),
	url(r'^team/create$','team_create'),
	url(r'^team/update/([\d]+)','team_update'),
	url(r'^team/update/process/([\d]+)','team_update_process'),
	url(r'^team/leave/process/([\d]+)','team_leave_process'),
	url(r'^team/join$','team_join'),
	url(r'^team/confirm/([\d]+)','team_confirm_process'),
	url(r'^team/cancel/([\d]+)','team_cancel_process'),
	url(r'^scoreboard$','scoreboard'),
	url(r'^statistic$','statistic'),
	url(r'^signup/form/([\w]+)', 'signup_form'),
	url(r'^signup$','signup'),
	url(r'^front-end-test$','frontend_test'),
)
