# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-01 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0008_auto_20160629_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('tries', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Problem')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('sicnumber', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(default='confirmed', max_length=255)),
                ('invitation_code', models.CharField(max_length=255)),
                ('point', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_list', models.CharField(max_length=255)),
                ('unknown_list', models.CharField(max_length=255)),
                ('todo_list', models.CharField(max_length=255)),
                ('problem_statement', models.CharField(max_length=255)),
                ('conclusion', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('point', models.IntegerField(default=0)),
                ('teacher_point', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Problem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Team')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.AddField(
            model_name='solve',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Team'),
        ),
    ]
