# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-01 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='salt',
            field=models.CharField(default='salt_value', max_length=255),
        ),
    ]
