# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_auto_20160710_0908'),
        ('student', '0002_student_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evsolv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Team')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
