# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-12 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_evsolv_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evsolv',
            name='student',
        ),
        migrations.RemoveField(
            model_name='evsolv',
            name='team',
        ),
        migrations.DeleteModel(
            name='Evsolv',
        ),
    ]
