# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_evsolv'),
    ]

    operations = [
        migrations.AddField(
            model_name='evsolv',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
