# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-12 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_evsolv_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['point']},
        ),
    ]
