# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-07-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20160712_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='teacher_point',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
